/**
 * Procedural actor sprites. Every character is drawn from primitives into
 * per-direction animation frames at boot. Frame counts and cell sizes are
 * declared alongside each actor so the gameplay code can stay art-agnostic.
 */
import type { Dir } from '../engine/math';
import { PAL, shade, withAlpha } from './palette';
import { Painter, makeCanvas, type Canvas } from './paint';

export interface AnimSet {
  /** Cell width/height in pixels. */
  w: number;
  h: number;
  /** Pixel offset from the actor's feet-centre to the cell's top-left. */
  ox: number;
  oy: number;
  frames: Record<Dir, Canvas[]>;
}

export interface ActorArt {
  idle: AnimSet;
  walk: AnimSet;
  attack?: AnimSet;
  hurt?: AnimSet;
}

const DIRS: Dir[] = ['down', 'up', 'left', 'right'];

function flipX(src: Canvas): Canvas {
  const { canvas, ctx } = makeCanvas(src.width, src.height);
  ctx.translate(src.width, 0);
  ctx.scale(-1, 1);
  ctx.drawImage(src, 0, 0);
  return canvas;
}

/**
 * Builds an AnimSet by calling `draw` for each direction/frame. `right` is
 * generated by mirroring `left` unless the drawer handles it explicitly.
 */
function buildAnim(
  w: number,
  h: number,
  ox: number,
  oy: number,
  count: number,
  draw: (p: Painter, dir: Dir, frame: number) => void,
  mirrorRight = true,
): AnimSet {
  const frames = {} as Record<Dir, Canvas[]>;
  for (const dir of DIRS) {
    if (dir === 'right' && mirrorRight) continue;
    const list: Canvas[] = [];
    for (let f = 0; f < count; f++) {
      const p = new Painter(w, h);
      draw(p, dir, f);
      list.push(p.canvas);
    }
    frames[dir] = list;
  }
  if (mirrorRight) frames.right = frames.left.map(flipX);
  return { w, h, ox, oy, frames };
}

// ---------------------------------------------------------------------------
// Hero
// ---------------------------------------------------------------------------

const HERO_W = 16;
const HERO_H = 20;

interface HeroPose {
  /** -1, 0 or 1: which leg leads. */
  step: number;
  /** Vertical body bob in pixels. */
  bob: number;
  /** Sword swing progress, 0 = sheathed. */
  swing?: number;
  shield?: boolean;
}

function heroLegs(p: Painter, step: number, baseY: number): void {
  const left = baseY + (step > 0 ? 0 : 1);
  const right = baseY + (step < 0 ? 0 : 1);
  p.rect(5, left, 3, 20 - left, PAL.boot);
  p.rect(8, right, 3, 20 - right, PAL.boot);
  p.hline(5, 19, 3, shade(PAL.boot, 0.7));
  p.hline(8, 19, 3, shade(PAL.boot, 0.7));
}

function heroTunicDown(p: Painter, y: number): void {
  p.rect(4, y, 8, 6, PAL.tunic);
  p.rect(4, y, 8, 1, PAL.tunicLight);
  p.rect(5, y + 5, 6, 1, PAL.tunicDark);
  // Sleeves.
  p.rect(3, y + 1, 2, 3, PAL.tunic);
  p.rect(11, y + 1, 2, 3, PAL.tunic);
  p.rect(3, y + 4, 2, 2, PAL.skin);
  p.rect(11, y + 4, 2, 2, PAL.skin);
  // Belt.
  p.rect(4, y + 4, 8, 1, PAL.woodDark);
  p.px(7, y + 4, PAL.gold);
}

function heroHeadDown(p: Painter, y: number): void {
  // Cap.
  p.rect(3, y, 10, 3, PAL.tunicDark);
  p.rect(4, y - 1, 8, 1, PAL.tunicDark);
  p.rect(4, y, 8, 2, PAL.tunic);
  // Face.
  p.rect(4, y + 3, 8, 5, PAL.skin);
  p.rect(4, y + 7, 8, 1, PAL.skinDark);
  // Hair fringe and side locks.
  p.rect(4, y + 3, 8, 1, PAL.hair);
  p.rect(3, y + 3, 1, 4, PAL.hair);
  p.rect(12, y + 3, 1, 4, PAL.hair);
  p.px(3, y + 6, PAL.hairDark);
  p.px(12, y + 6, PAL.hairDark);
  // Eyes.
  p.rect(5, y + 5, 2, 2, PAL.black);
  p.rect(9, y + 5, 2, 2, PAL.black);
  p.px(6, y + 5, PAL.white);
  p.px(10, y + 5, PAL.white);
}

function heroHeadUp(p: Painter, y: number): void {
  p.rect(3, y, 10, 3, PAL.tunicDark);
  p.rect(4, y - 1, 8, 1, PAL.tunicDark);
  p.rect(4, y, 8, 2, PAL.tunic);
  // Back of the head is all hair.
  p.rect(4, y + 3, 8, 5, PAL.hair);
  p.rect(4, y + 3, 8, 1, PAL.hairDark);
  p.rect(4, y + 7, 8, 1, PAL.hairDark);
  p.px(5, y + 5, PAL.hairDark);
  p.px(10, y + 5, PAL.hairDark);
}

function heroHeadSide(p: Painter, y: number): void {
  p.rect(3, y, 10, 3, PAL.tunicDark);
  p.rect(3, y - 1, 6, 1, PAL.tunicDark);
  p.rect(4, y, 8, 2, PAL.tunic);
  p.rect(4, y + 3, 8, 5, PAL.skin);
  p.rect(4, y + 7, 8, 1, PAL.skinDark);
  // Hair sweeps back; ear and one eye visible.
  p.rect(9, y + 3, 4, 5, PAL.hair);
  p.rect(4, y + 3, 5, 1, PAL.hair);
  p.rect(5, y + 5, 2, 2, PAL.black);
  p.px(5, y + 5, PAL.white);
  p.px(8, y + 6, PAL.skinDark);
}

function heroTunicSide(p: Painter, y: number): void {
  p.rect(4, y, 8, 6, PAL.tunic);
  p.rect(4, y, 8, 1, PAL.tunicLight);
  p.rect(5, y + 5, 6, 1, PAL.tunicDark);
  p.rect(5, y + 1, 3, 4, PAL.tunic);
  p.rect(5, y + 4, 3, 2, PAL.skin);
  p.rect(4, y + 4, 8, 1, PAL.woodDark);
}

function heroTunicUp(p: Painter, y: number): void {
  p.rect(4, y, 8, 6, PAL.tunic);
  p.rect(4, y, 8, 1, PAL.tunicLight);
  p.rect(3, y + 1, 2, 3, PAL.tunic);
  p.rect(11, y + 1, 2, 3, PAL.tunic);
  p.rect(3, y + 4, 2, 2, PAL.skin);
  p.rect(11, y + 4, 2, 2, PAL.skin);
  p.rect(4, y + 4, 8, 1, PAL.woodDark);
  // Scabbard slung across the back.
  p.line(5, y + 1, 10, y + 5, PAL.woodDark);
  p.line(5, y, 10, y + 4, PAL.steelDark);
}

/** Draws a sword blade at a rotation appropriate to `dir` and `t` in [0,1]. */
function heroSword(p: Painter, dir: Dir, t: number): void {
  // Sweep runs from behind the hero to in front of them.
  const angles: Record<Dir, [number, number]> = {
    down: [-0.6, 1.9],
    up: [Math.PI + 0.6, Math.PI - 1.9],
    left: [Math.PI * 0.5 + 0.4, Math.PI * 1.5 - 0.4],
    right: [Math.PI * 0.5 - 0.4, -Math.PI * 0.5 + 0.4],
  };
  const [a0, a1] = angles[dir];
  const a = a0 + (a1 - a0) * t;
  const cx = 8;
  const cy = 12;
  const len = 11;
  const tipX = Math.round(cx + Math.cos(a - Math.PI / 2) * len);
  const tipY = Math.round(cy + Math.sin(a - Math.PI / 2) * len);
  const hiltX = Math.round(cx + Math.cos(a - Math.PI / 2) * 3);
  const hiltY = Math.round(cy + Math.sin(a - Math.PI / 2) * 3);
  p.line(hiltX, hiltY, tipX, tipY, PAL.steelLight);
  p.line(hiltX + 1, hiltY, tipX, tipY + 1, PAL.steel);
  p.px(hiltX, hiltY, PAL.gold);
  p.px(tipX, tipY, PAL.white);
}

function heroShield(p: Painter, dir: Dir): void {
  if (dir === 'up') return; // Shield is hidden behind the hero.
  const x = dir === 'left' ? 2 : dir === 'right' ? 11 : 11;
  p.rect(x, 11, 4, 6, PAL.steelDark);
  p.rect(x, 11, 4, 1, PAL.steelLight);
  p.rect(x + 1, 12, 2, 3, PAL.bronze);
  p.px(x + 1, 13, PAL.goldLight);
}

function drawHero(p: Painter, dir: Dir, pose: HeroPose): void {
  const bodyY = 10 + pose.bob;
  const headY = 2 + pose.bob;
  heroLegs(p, pose.step, 16);
  if (dir === 'down') {
    heroTunicDown(p, bodyY);
    heroHeadDown(p, headY);
  } else if (dir === 'up') {
    heroTunicUp(p, bodyY);
    heroHeadUp(p, headY);
  } else {
    heroTunicSide(p, bodyY);
    heroHeadSide(p, headY);
  }
  if (pose.shield) heroShield(p, dir);
  if (pose.swing !== undefined) heroSword(p, dir, pose.swing);
}

function buildHeroArt(): ActorArt & { shieldSet: AnimSet; spin: AnimSet } {
  const idle = buildAnim(HERO_W, HERO_H, -8, -18, 2, (p, dir, f) =>
    drawHero(p, dir, { step: 0, bob: f === 1 ? 1 : 0 }),
  );
  const walk = buildAnim(HERO_W, HERO_H, -8, -18, 4, (p, dir, f) => {
    const cycle = [1, 0, -1, 0][f];
    drawHero(p, dir, { step: cycle, bob: f % 2 === 0 ? 0 : 1 });
  });
  const attack = buildAnim(HERO_W, HERO_H, -8, -18, 4, (p, dir, f) =>
    drawHero(p, dir, { step: 0, bob: 0, swing: f / 3 }),
  );
  const shieldSet = buildAnim(HERO_W, HERO_H, -8, -18, 1, (p, dir) =>
    drawHero(p, dir, { step: 0, bob: 0, shield: true }),
  );
  const spin = buildAnim(HERO_W, HERO_H, -8, -18, 8, (p, dir, f) =>
    drawHero(p, dir, { step: 0, bob: 0, swing: f / 7 }),
  );
  return { idle, walk, attack, shieldSet, spin };
}

// ---------------------------------------------------------------------------
// Enemies
// ---------------------------------------------------------------------------

function drawSlime(p: Painter, frame: number): void {
  // Squash-and-stretch hop.
  const squash = [0, 1, 2, 1][frame];
  const h = 9 - squash;
  const w = 6 + squash;
  const y = 15 - h;
  p.ellipse(8, y + h / 2, w, h / 2, PAL.slimeDark);
  p.ellipse(8, y + h / 2 + 0.5, w - 1.5, h / 2 - 1, PAL.slime);
  p.ellipse(6, y + 2, 2, 1.4, PAL.slimeLight);
  p.rect(6, y + 3, 2, 2, PAL.black);
  p.rect(10, y + 3, 2, 2, PAL.black);
  p.px(6, y + 3, PAL.white);
  p.px(10, y + 3, PAL.white);
  p.hline(4, 15, 9, withAlpha(PAL.slimeDark, 0.7));
}

function drawOctorok(p: Painter, dir: Dir, frame: number): void {
  const bob = frame % 2;
  const y = 4 + bob;
  p.ellipse(8, y + 5, 6, 5, PAL.bloodDark);
  p.ellipse(8, y + 4.5, 5, 4, PAL.blood);
  p.ellipse(6.5, y + 3, 2.5, 1.8, PAL.bloodLight);
  // Tentacle feet.
  for (let i = 0; i < 3; i++) {
    const fx = 4 + i * 4;
    p.rect(fx, 14 - bob, 2, 3, PAL.bloodDark);
    p.px(fx, 16 - bob, PAL.blood);
  }
  // Eyes / snout depend on facing.
  if (dir === 'up') {
    p.rect(5, y + 2, 2, 2, PAL.black);
    p.rect(9, y + 2, 2, 2, PAL.black);
  } else if (dir === 'down') {
    p.rect(5, y + 4, 2, 2, PAL.eyeWhite);
    p.rect(9, y + 4, 2, 2, PAL.eyeWhite);
    p.px(6, y + 5, PAL.pupil);
    p.px(10, y + 5, PAL.pupil);
    p.rect(7, y + 7, 2, 2, PAL.bloodDark);
  } else {
    p.rect(4, y + 4, 2, 2, PAL.eyeWhite);
    p.px(4, y + 5, PAL.pupil);
    p.rect(2, y + 6, 3, 2, PAL.bloodDark);
  }
}

function drawKeese(p: Painter, frame: number): void {
  const flap = [0, 2, 3, 2][frame];
  p.ellipse(8, 9, 3, 3.4, PAL.batDark);
  p.ellipse(8, 8.5, 2.2, 2.6, PAL.bat);
  p.px(6, 8, PAL.bloodLight);
  p.px(10, 8, PAL.bloodLight);
  // Wings sweep up and down with the flap phase.
  for (const side of [-1, 1]) {
    const x = 8 + side * 3;
    p.line(x, 8, x + side * 5, 8 - flap, PAL.batDark);
    p.line(x, 10, x + side * 5, 10 - flap + 1, PAL.batDark);
    p.line(x + side * 2, 9, x + side * 5, 9 - flap, PAL.batLight);
  }
  p.px(7, 12, PAL.batDark).px(9, 12, PAL.batDark);
}

function drawStalfos(p: Painter, dir: Dir, frame: number): void {
  const step = frame % 2 === 0 ? 0 : 1;
  // Legs and skirt of bone.
  p.rect(5, 15 + step, 2, 4 - step, PAL.plaster);
  p.rect(9, 16 - step, 2, 3 + step, PAL.plaster);
  p.rect(4, 10, 8, 6, PAL.steelDark);
  p.rect(4, 10, 8, 1, PAL.steel);
  p.rect(5, 14, 6, 1, shade(PAL.steelDark, 0.75));
  // Helm.
  p.rect(4, 3, 8, 7, PAL.steel);
  p.rect(4, 3, 8, 1, PAL.steelLight);
  p.rect(3, 5, 10, 2, PAL.steelDark);
  if (dir === 'down') {
    p.rect(5, 6, 2, 2, PAL.black);
    p.rect(9, 6, 2, 2, PAL.black);
    p.px(5, 6, PAL.fireLight);
    p.px(9, 6, PAL.fireLight);
  } else if (dir !== 'up') {
    p.rect(4, 6, 2, 2, PAL.black);
    p.px(4, 6, PAL.fireLight);
  }
  // Shield faces the direction of travel; that side is armoured.
  if (dir === 'left') p.rect(1, 9, 3, 7, PAL.bronze);
  else if (dir === 'right') p.rect(12, 9, 3, 7, PAL.bronze);
  else if (dir === 'down') p.rect(11, 10, 4, 6, PAL.bronze);
  else p.rect(1, 10, 4, 6, shade(PAL.bronze, 0.7));
}

function drawThornling(p: Painter, frame: number): void {
  const open = frame % 2 === 0;
  p.rect(7, 12, 2, 5, PAL.plantDark);
  p.line(6, 14, 3, 12, PAL.plantDark);
  p.line(10, 14, 13, 12, PAL.plantDark);
  p.ellipse(8, 9, 5, 5, PAL.plantDark);
  p.ellipse(8, 9, 4, 4, PAL.plant);
  if (open) {
    p.ellipse(8, 9, 2.6, 2.6, PAL.bloodDark);
    p.ellipse(8, 9, 1.4, 1.4, PAL.eyeWhite);
    p.px(8, 9, PAL.pupil);
    // Teeth.
    for (let i = 0; i < 4; i++) p.px(6 + i * 1.5, 7, PAL.white);
  } else {
    p.ellipse(8, 9, 3, 3, PAL.plantLight);
    p.hline(6, 9, 5, PAL.plantDark);
  }
}

// ---------------------------------------------------------------------------
// Boss: Thornmaw, Root of the Hollow
// ---------------------------------------------------------------------------

const BOSS_W = 48;
const BOSS_H = 48;

function drawThornmaw(p: Painter, frame: number, state: 'idle' | 'open' | 'hurt'): void {
  const pulse = frame % 2;
  const body = state === 'hurt' ? PAL.bloodDark : PAL.plantDark;
  const bodyLight = state === 'hurt' ? PAL.blood : PAL.plant;

  // Root tendrils spreading from the base.
  for (let i = 0; i < 6; i++) {
    const a = (i / 6) * Math.PI * 2 + frame * 0.1;
    const x = 24 + Math.cos(a) * 18;
    const y = 34 + Math.sin(a) * 10;
    p.line(24, 34, Math.round(x), Math.round(y), PAL.plantDark);
    p.px(Math.round(x), Math.round(y), PAL.woodDark);
  }

  // Bulb.
  p.ellipse(24, 26, 17, 16, body);
  p.ellipse(24, 25, 15, 14, bodyLight);
  p.ellipse(17, 18, 6, 5, PAL.plantLight);

  // Petals ringing the maw.
  for (let i = 0; i < 8; i++) {
    const a = (i / 8) * Math.PI * 2 + (pulse ? 0.15 : 0);
    const px1 = 24 + Math.cos(a) * 11;
    const py1 = 24 + Math.sin(a) * 10;
    const px2 = 24 + Math.cos(a) * (state === 'open' ? 18 : 15);
    const py2 = 24 + Math.sin(a) * (state === 'open' ? 17 : 14);
    p.line(Math.round(px1), Math.round(py1), Math.round(px2), Math.round(py2), PAL.bloodDark);
    p.px(Math.round(px2), Math.round(py2), PAL.white);
  }

  if (state === 'open' || state === 'hurt') {
    // Exposed eye — the only vulnerable moment.
    p.ellipse(24, 24, 9, 8, PAL.bloodDark);
    p.ellipse(24, 24, 7, 6, PAL.eyeWhite);
    p.ellipse(24, 24, 3.5, 4, PAL.pupil);
    p.ellipse(24, 24, 2, 2.4, state === 'hurt' ? PAL.fire : PAL.bloodLight);
    p.px(22, 22, PAL.white);
  } else {
    // Clamped shut.
    p.ellipse(24, 24, 9, 8, PAL.plantDark);
    p.hline(15, 24, 18, PAL.black);
    for (let i = 0; i < 7; i++) {
      p.px(16 + i * 3, 23, PAL.white);
      p.px(17 + i * 3, 25, PAL.white);
    }
  }
}

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

export interface ActorLibrary {
  hero: ActorArt & { shieldSet: AnimSet; spin: AnimSet };
  slime: ActorArt;
  octorok: ActorArt;
  keese: ActorArt;
  stalfos: ActorArt;
  thornling: ActorArt;
  boss: { idle: Canvas[]; open: Canvas[]; hurt: Canvas[]; w: number; h: number; ox: number; oy: number };
}

function omniAnim(w: number, h: number, ox: number, oy: number, count: number, draw: (p: Painter, f: number) => void): AnimSet {
  // Actors that look the same from every angle share one frame list.
  const list: Canvas[] = [];
  for (let f = 0; f < count; f++) {
    const p = new Painter(w, h);
    draw(p, f);
    list.push(p.canvas);
  }
  return { w, h, ox, oy, frames: { down: list, up: list, left: list, right: list } };
}

export function buildActorLibrary(): ActorLibrary {
  const bossFrames = (state: 'idle' | 'open' | 'hurt') => {
    const list: Canvas[] = [];
    for (let f = 0; f < 2; f++) {
      const p = new Painter(BOSS_W, BOSS_H);
      drawThornmaw(p, f, state);
      list.push(p.canvas);
    }
    return list;
  };

  return {
    hero: buildHeroArt(),
    slime: {
      idle: omniAnim(16, 16, -8, -14, 4, (p, f) => drawSlime(p, f)),
      walk: omniAnim(16, 16, -8, -14, 4, (p, f) => drawSlime(p, f)),
    },
    octorok: {
      idle: buildAnim(16, 18, -8, -16, 2, (p, dir, f) => drawOctorok(p, dir, f)),
      walk: buildAnim(16, 18, -8, -16, 2, (p, dir, f) => drawOctorok(p, dir, f)),
    },
    keese: {
      idle: omniAnim(16, 16, -8, -13, 4, (p, f) => drawKeese(p, f)),
      walk: omniAnim(16, 16, -8, -13, 4, (p, f) => drawKeese(p, f)),
    },
    stalfos: {
      idle: buildAnim(16, 20, -8, -18, 2, (p, dir, f) => drawStalfos(p, dir, f)),
      walk: buildAnim(16, 20, -8, -18, 2, (p, dir, f) => drawStalfos(p, dir, f)),
    },
    thornling: {
      idle: omniAnim(16, 18, -8, -16, 2, (p, f) => drawThornling(p, f)),
      walk: omniAnim(16, 18, -8, -16, 2, (p, f) => drawThornling(p, f)),
    },
    boss: {
      idle: bossFrames('idle'),
      open: bossFrames('open'),
      hurt: bossFrames('hurt'),
      w: BOSS_W,
      h: BOSS_H,
      ox: -24,
      oy: -42,
    },
  };
}
