/**
 * The Drowned Bell — a second dungeon under the marsh, 3x3 chambers.
 *
 *   (0,0) Reliquary         (1,0) Tideheart's Nave   (2,0) Wight's Choir
 *   (0,1) Flooded Gallery   (1,1) Bell Hub           (2,1) Candle Crypt
 *   (0,2) Drowned Cellar    (1,2) Bellmouth Landing  (2,2) Lantern Vault
 *
 * Chamber walls are generated by `chamber()` so only the 16x9 interior is
 * authored by hand — same shell as the Hollow Root, so doorways line up.
 */
import type { MapDef } from '../types';
import { link } from '../types';

type Exit = 'n' | 's' | 'e' | 'w';

interface Doors {
  n?: string;
  s?: string;
  e?: string;
  w?: string;
}

const W = 'W';

function chamber(exits: string, interior: string[], doors: Doors = {}): string[] {
  const has = (e: Exit) => exits.includes(e);
  const wall9 = W.repeat(9);
  const gap = (open: boolean, leaf?: string) => (open ? (leaf ? leaf + leaf : '  ') : W + W);

  const rows: string[] = [];
  rows.push(wall9 + (has('n') ? '//' : W + W) + wall9);
  rows.push(wall9 + gap(has('n'), doors.n) + wall9);

  for (let i = 0; i < 9; i++) {
    const sideRow = i === 4 || i === 5;
    const left = has('w') && sideRow ? (doors.w ? doors.w + doors.w : '//') : W + W;
    const right = has('e') && sideRow ? (doors.e ? doors.e + doors.e : '//') : W + W;
    rows.push(left + interior[i] + right);
  }

  rows.push(wall9 + gap(has('s'), doors.s) + wall9);
  rows.push(wall9 + (has('s') ? '//' : W + W) + wall9);
  return rows;
}

export const DROWNED: MapDef = {
  id: 'drowned',
  name: 'The Drowned Bell',
  cols: 3,
  rows: 3,
  music: 'drowned',
  dungeon: true,
  rooms: [
    // ---------------------------------------------------------------- (1,2)
    {
      rx: 1,
      ry: 2,
      name: 'Bellmouth Landing',
      rows: chamber('nwe', [
        '                ',
        '   ss      ss   ',
        '   s        s   ',
        '                ',
        '                ',
        '                ',
        '   tt      tt   ',
        '       <<       ',
        '                ',
      ]),
      spawns: [{ kind: 'sign', x: 6, y: 4, opts: { text: 'bellEntry' } }],
      links: {
        '9,9': link('overworld', 3, 3, 9, 8, 'stairs'),
        '10,9': link('overworld', 3, 3, 10, 8, 'stairs'),
      },
    },

    // ---------------------------------------------------------------- (0,2)
    {
      rx: 0,
      ry: 2,
      name: 'Drowned Cellar',
      rows: chamber('e', [
        '                ',
        '  WW      WW    ',
        '  W   ss   W    ',
        '     ssss       ',
        '     ssss       ',
        '     ssss       ',
        '  W   ss   W    ',
        '  WW      WW    ',
        '                ',
      ]),
      lockOnEnemies: true,
      spawns: [
        { kind: 'crab', x: 6, y: 4 },
        { kind: 'crab', x: 13, y: 8 },
        { kind: 'wisp', x: 9, y: 6 },
        { kind: 'pot', x: 4, y: 3 },
        { kind: 'pot', x: 15, y: 9 },
        { kind: 'chest', x: 9, y: 3, opts: { loot: 'smallKey' } },
      ],
    },

    // ---------------------------------------------------------------- (2,2)
    {
      rx: 2,
      ry: 2,
      name: 'Lantern Vault',
      rows: chamber('w', [
        '  WWWWWWWWWWWW  ',
        '  Wt        tW  ',
        '  W   cccc   W  ',
        '  W   cccc   W  ',
        '      cccc      ',
        '      cccc      ',
        '  W   cccc   W  ',
        '  Wt        tW  ',
        '  WWWWWWWWWWWW  ',
      ], { w: 'L' }),
      spawns: [{ kind: 'chest', x: 9, y: 5, opts: { loot: 'lantern', big: true } }],
    },

    // ---------------------------------------------------------------- (1,1)
    {
      rx: 1,
      ry: 1,
      name: 'Bell Hub',
      rows: chamber('nswe', [
        '  W          W  ',
        '  W   rrrr   W  ',
        '      rrrr      ',
        '      rrrr      ',
        '      rrrr      ',
        '      rrrr      ',
        '      rrrr      ',
        '  W   rrrr   W  ',
        '  W          W  ',
      ], { n: 'B', w: 'L' }),
      lockOnEnemies: true,
      spawns: [
        { kind: 'wisp', x: 5, y: 4 },
        { kind: 'crab', x: 14, y: 8 },
        { kind: 'stalfos', x: 9, y: 3 },
        { kind: 'chest', x: 9, y: 9, opts: { loot: 'smallKey' } },
        { kind: 'sign', x: 6, y: 9, opts: { text: 'bellHub' } },
      ],
    },

    // ---------------------------------------------------------------- (0,1)
    {
      rx: 0,
      ry: 1,
      name: 'Flooded Gallery',
      rows: chamber('ne', [
        '                ',
        '  SS  ss  SS    ',
        '      ss        ',
        '    SS  ss  SS  ',
        '        ss      ',
        '        ss      ',
        '  SS  ss  SS    ',
        '      ss        ',
        '    SS  ss  SS  ',
      ], { n: 'C' }),
      spawns: [
        { kind: 'crab', x: 6, y: 4 },
        { kind: 'wisp', x: 12, y: 8 },
        { kind: 'keese', x: 9, y: 6 },
        { kind: 'sign', x: 4, y: 6, opts: { text: 'cracked' } },
      ],
    },

    // ---------------------------------------------------------------- (0,0)
    {
      rx: 0,
      ry: 0,
      name: 'Reliquary',
      rows: chamber('s', [
        '  WWWWWWWWWWWW  ',
        '  W          W  ',
        '  W  rrrrrr  W  ',
        '  W  r    r  W  ',
        '  W  r    r  W  ',
        '  W  r    r  W  ',
        '  W  rrrrrr  W  ',
        '  W          W  ',
        '  WWWW    WWWW  ',
      ]),
      spawns: [
        { kind: 'chest', x: 9, y: 5, opts: { loot: 'dungeonMap', big: true } },
        { kind: 'chest', x: 9, y: 7, opts: { loot: 'heartPiece', big: true } },
      ],
    },

    // ---------------------------------------------------------------- (2,1)
    {
      rx: 2,
      ry: 1,
      name: 'Candle Crypt',
      dark: true,
      rows: chamber('nw', [
        '                ',
        '   tt      tt   ',
        '                ',
        '                ',
        '                ',
        '                ',
        '                ',
        '   tt      tt   ',
        '                ',
      ], { n: '+' }),
      lockOnEnemies: true,
      spawns: [
        { kind: 'wisp', x: 5, y: 4 },
        { kind: 'wisp', x: 14, y: 8 },
        { kind: 'keese', x: 9, y: 6 },
        { kind: 'chest', x: 9, y: 5, opts: { loot: 'compass', big: true } },
      ],
    },

    // ---------------------------------------------------------------- (2,0)
    {
      rx: 2,
      ry: 0,
      name: "Wight's Choir",
      rows: chamber('s', [
        '  WWWWWWWWWWWW  ',
        '  W          W  ',
        '  W  W    W  W  ',
        '  W          W  ',
        '  W          W  ',
        '  W          W  ',
        '  W  W    W  W  ',
        '  W          W  ',
        '  WWWW    WWWW  ',
      ]),
      spawns: [{ kind: 'bellwight', x: 9, y: 5 }],
    },

    // ---------------------------------------------------------------- (1,0)
    {
      rx: 1,
      ry: 0,
      name: "Tideheart's Nave",
      music: 'boss',
      rows: chamber('s', [
        '  WWWWWWWWWWWW  ',
        '  Wr        rW  ',
        '  W          W  ',
        '  W          W  ',
        '  W          W  ',
        '  W          W  ',
        '  W          W  ',
        '  Wr        rW  ',
        '  WWWW    WWWW  ',
      ]),
      spawns: [{ kind: 'tideheart', x: 9, y: 5 }],
    },
  ],
};
