/**
 * The Hollow Root — the game's dungeon, a 4x3 grid of chambers.
 *
 *   (0,0) Forgotten Cache   (1,0) Thornmaw's Root   (2,0) Warden's Cell
 *   (0,1) Spiked Gallery    (1,1) Hollow Hub        (2,1) Bone Ward     (3,1) Ember Vault
 *   (0,2) Pot Cellar        (1,2) Root Landing      (2,2) Chasm Walk    (3,2) Bowyer's Vault
 *
 * Chamber walls are generated by `chamber()` so only the 16x9 interior is
 * authored by hand — that keeps every doorway aligned across the whole floor.
 */
import type { MapDef } from '../types';
import { link } from '../types';

type Exit = 'n' | 's' | 'e' | 'w';

interface Doors {
  n?: string;
  s?: string;
  e?: string;
  w?: string;
}

const W = 'W';

/**
 * Wraps a 16x9 interior in a dungeon shell.
 *
 * Doorways sit at columns 9-10 (north/south) and rows 6-7 (east/west). Pass
 * `doors` to place a door leaf in the opening: '+' room-lock, 'L' locked,
 * 'B' boss, 'C' cracked wall.
 */
function chamber(exits: string, interior: string[], doors: Doors = {}): string[] {
  const has = (e: Exit) => exits.includes(e);
  const wall9 = W.repeat(9);
  const gap = (open: boolean, leaf?: string) => (open ? (leaf ? leaf + leaf : '  ') : W + W);

  const rows: string[] = [];
  rows.push(wall9 + (has('n') ? '//' : W + W) + wall9);
  rows.push(wall9 + gap(has('n'), doors.n) + wall9);

  for (let i = 0; i < 9; i++) {
    const sideRow = i === 4 || i === 5;
    const left = has('w') && sideRow ? (doors.w ? doors.w + doors.w : '//') : W + W;
    const right = has('e') && sideRow ? (doors.e ? doors.e + doors.e : '//') : W + W;
    rows.push(left + interior[i] + right);
  }

  rows.push(wall9 + gap(has('s'), doors.s) + wall9);
  rows.push(wall9 + (has('s') ? '//' : W + W) + wall9);
  return rows;
}

export const DUNGEON: MapDef = {
  id: 'dungeon',
  name: 'The Hollow Root',
  cols: 4,
  rows: 3,
  music: 'dungeon',
  dungeon: true,
  rooms: [
    // ---------------------------------------------------------------- (1,2)
    {
      rx: 1,
      ry: 2,
      name: 'Root Landing',
      rows: chamber('nwe', [
        '                ',
        '   uu      uu   ',
        '   u        u   ',
        '                ',
        '                ',
        '                ',
        '   tt      tt   ',
        '       <<       ',
        '                ',
      ]),
      spawns: [{ kind: 'sign', x: 6, y: 4, opts: { text: 'dungeonEntry' } }],
      links: {
        '9,9': link('overworld', 1, 0, 9, 2, 'stairs'),
        '10,9': link('overworld', 1, 0, 10, 2, 'stairs'),
      },
    },

    // ---------------------------------------------------------------- (0,2)
    {
      rx: 0,
      ry: 2,
      name: 'Pot Cellar',
      rows: chamber('e', [
        '                ',
        '  WW      WW    ',
        '  W        W    ',
        '                ',
        '                ',
        '                ',
        '  W        W    ',
        '  WW      WW    ',
        '                ',
      ]),
      lockOnEnemies: true,
      spawns: [
        { kind: 'thornling', x: 6, y: 4 },
        { kind: 'thornling', x: 13, y: 8 },
        { kind: 'slime', x: 9, y: 6 },
        { kind: 'pot', x: 4, y: 3 },
        { kind: 'pot', x: 5, y: 3 },
        { kind: 'pot', x: 15, y: 9 },
        { kind: 'pot', x: 14, y: 9 },
        { kind: 'chest', x: 9, y: 3, opts: { loot: 'smallKey' } },
      ],
    },

    // ---------------------------------------------------------------- (2,2)
    {
      rx: 2,
      ry: 2,
      name: 'Chasm Walk',
      rows: chamber('we', [
        '                ',
        '  PPPPPPPPPPPP  ',
        '  PPPPPPPPPPPP  ',
        '  PP        PP  ',
        '     PP   PP    ',
        '     PP   PP    ',
        '  PP        PP  ',
        '  PPPPPPPPPPPP  ',
        '                ',
      ], { e: 'L' }),
      spawns: [
        { kind: 'keese', x: 6, y: 5 },
        { kind: 'keese', x: 13, y: 7 },
        { kind: 'keese', x: 9, y: 4 },
      ],
    },

    // ---------------------------------------------------------------- (3,2)
    {
      rx: 3,
      ry: 2,
      name: "Bowyer's Vault",
      rows: chamber('w', [
        '  WWWWWWWWWWWW  ',
        '  W          W  ',
        '  W   cccc   W  ',
        '  W   cccc   W  ',
        '      cccc      ',
        '      cccc      ',
        '  W   cccc   W  ',
        '  W          W  ',
        '  WWWWWWWWWWWW  ',
      ]),
      spawns: [{ kind: 'chest', x: 9, y: 5, opts: { loot: 'bow', big: true } }],
    },

    // ---------------------------------------------------------------- (1,1)
    {
      rx: 1,
      ry: 1,
      name: 'Hollow Hub',
      rows: chamber('nswe', [
        '  W          W  ',
        '  W   FFFF   W  ',
        '      FFFF      ',
        '      FFFF      ',
        '      FFFF      ',
        '      FFFF      ',
        '      FFFF      ',
        '  W   FFFF   W  ',
        '  W          W  ',
      ], { n: 'B', w: 'L' }),
      spawns: [
        { kind: 'stalfos', x: 5, y: 4 },
        { kind: 'stalfos', x: 14, y: 8 },
        { kind: 'thornling', x: 9, y: 3 },
        { kind: 'sign', x: 6, y: 9, opts: { text: 'hub' } },
      ],
    },

    // ---------------------------------------------------------------- (0,1)
    {
      rx: 0,
      ry: 1,
      name: 'Spiked Gallery',
      rows: chamber('ne', [
        '                ',
        '  SS  SS  SS    ',
        '                ',
        '    SS  SS  SS  ',
        '                ',
        '                ',
        '  SS  SS  SS    ',
        '                ',
        '    SS  SS  SS  ',
      ], { n: 'C' }),
      spawns: [
        { kind: 'keese', x: 6, y: 4 },
        { kind: 'keese', x: 12, y: 8 },
        { kind: 'thornling', x: 9, y: 6 },
        { kind: 'sign', x: 4, y: 6, opts: { text: 'cracked' } },
      ],
    },

    // ---------------------------------------------------------------- (0,0)
    {
      rx: 0,
      ry: 0,
      name: 'Forgotten Cache',
      rows: chamber('s', [
        '  WWWWWWWWWWWW  ',
        '  W          W  ',
        '  W  rrrrrr  W  ',
        '  W  r    r  W  ',
        '  W  r    r  W  ',
        '  W  r    r  W  ',
        '  W  rrrrrr  W  ',
        '  W          W  ',
        '  WWWW    WWWW  ',
      ]),
      spawns: [{ kind: 'chest', x: 9, y: 6, opts: { loot: 'heartPiece', big: true } }],
    },

    // ---------------------------------------------------------------- (2,1)
    {
      rx: 2,
      ry: 1,
      name: 'Bone Ward',
      rows: chamber('nwe', [
        '                ',
        '   WW      WW   ',
        '                ',
        '                ',
        '                ',
        '                ',
        '                ',
        '   WW      WW   ',
        '                ',
      ], { n: '+' }),
      lockOnEnemies: true,
      spawns: [
        { kind: 'stalfos', x: 5, y: 4 },
        { kind: 'stalfos', x: 14, y: 8 },
        { kind: 'stalfos', x: 9, y: 9 },
        { kind: 'keese', x: 9, y: 3 },
        { kind: 'chest', x: 9, y: 6, opts: { loot: 'smallKey' } },
      ],
    },

    // ---------------------------------------------------------------- (3,1)
    {
      rx: 3,
      ry: 1,
      name: 'Ember Vault',
      dark: true,
      rows: chamber('w', [
        '  WWWWWWWWWWWW  ',
        '  Wt        tW  ',
        '  W          W  ',
        '  W  rrrrrr  W  ',
        '     rrrrrr     ',
        '     rrrrrr     ',
        '  W  rrrrrr  W  ',
        '  Wt        tW  ',
        '  WWWWWWWWWWWW  ',
      ]),
      spawns: [
        { kind: 'keese', x: 6, y: 4 },
        { kind: 'keese', x: 13, y: 8 },
        { kind: 'chest', x: 9, y: 6, opts: { loot: 'random', tier: 4 } },
      ],
    },

    // ---------------------------------------------------------------- (2,0)
    {
      rx: 2,
      ry: 0,
      name: "Warden's Cell",
      rows: chamber('s', [
        '  WWWWWWWWWWWW  ',
        '  W          W  ',
        '  W  W    W  W  ',
        '  W          W  ',
        '  W          W  ',
        '  W          W  ',
        '  W  W    W  W  ',
        '  W          W  ',
        '  WWWW    WWWW  ',
      ]),
      spawns: [{ kind: 'miniboss', x: 9, y: 5 }],
    },

    // ---------------------------------------------------------------- (1,0)
    {
      rx: 1,
      ry: 0,
      name: "Thornmaw's Root",
      music: 'boss',
      rows: chamber('s', [
        '  WWWWWWWWWWWW  ',
        '  Wr        rW  ',
        '  W          W  ',
        '  W          W  ',
        '  W          W  ',
        '  W          W  ',
        '  W          W  ',
        '  Wr        rW  ',
        '  WWWW    WWWW  ',
      ]),
      spawns: [{ kind: 'boss', x: 9, y: 5 }],
    },
  ],
};
